name: Build Allegro.DotnetSdk

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Allegro.DotnetSdk/**'
      - 'src/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Allegro.DotnetSdk/**'
      - 'src/*'

jobs:
  ci:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.DotnetSdk
