name: Build Allegro.DotnetSdk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.DotnetSdk
